
version: '2'
services:
  go-server:
    image: gocd/gocd-server:v20.1.0
    restart: always    
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./godata:/godata
  go-agent:
    build:
      context: ./gocd-agent
    restart: always
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      GO_SERVER_URL: http://go-server:8153/go
